def abcd():
    pass



total_sectors_n_industries = {'Education': ['Secondary Education',
  'Children',
  'E-Learning',
  'Universities',
  'Charter Schools',
  'Corporate Training',
  'Education',
  'Tutoring',
  'Higher Education',
  'Vocational Education',
  'Primary Education',
  'EdTech',
  'Continuing Education',
  'STEM Education',
  'Textbook',
  'EdTech',
  'Ediscovery',
  'College Recruiting'],
 'Business_Products_And_Services': ['Office Administration',
  'Social Media Marketing',
  'Assisted Living',
  'Commercial',
  'Price Comparison',
  'Local Advertising',
  'Social Impact',
  'Shipping Broker',
  'Charity',
  'Call Center',
  'Lead Generation',
  'Career Planning',
  'Enterprise',
  'Transaction Processing',
  'Information Services',
  'Laundry and Dry-cleaning',
  'Market Research',
  'Brand Marketing',
  'Freelance',
  'Translation Service',
  'Service Industry',
  'Local',
  'Subscription Service',
  'Supply Chain Management',
  'Loyalty Programs',
  'Contact Management',
  'Creative Agency',
  'Association',
  'Wholesale',
  'Franchise',
  'Social Media Management',
  'Warehousing',
  'B2C',
  'Coworking',
  'CRM',
  'Business Travel',
  'Management Consulting',
  'Direct Sales',
  'Small and Medium Businesses',
  'Virtual Workforce',
  'Facility Management',
  'Consulting',
  'Email Marketing',
  'Marketing',
  'Ticketing',
  'Reservations',
  'Trade Shows',
  'Legal',
  'Self-Storage',
  'Public Relations',
  'Customer Service',
  'Local Business',
  'B2B',
  'Non Profit',
  'Accounting',
  'Outsourcing',
  'Alumni',
  'Interior Design',
  'Business Development',
  'Lead Management',
  'Advice',
  'Procurement',
  'Knowledge Management',
  'Innovation Management',
  'Digital Marketing',
  'Intellectual Property',
  'Sales',
  'Quality Assurance',
  'Product Management',
  'Billing',
  'Professional Services',
  'Social Entrepreneurship',
  'Product Research',
  'Facilities Support Services',
  'Collection Agency',
  'Risk_And_Security',
  'Real_Estate',
  'Incubators',
  'Commercial Lending',
  'Penetration Testing'],
 'Software': ['Consumer Software',
  'Meeting Software',
  'IaaS',
  'Product Design',
  'Virtualization',
  'Industrial Automation',
  'Application Specific Integrated Circuit (ASIC)',
  'Management Information Systems',
  'Document Management',
  'Affiliate Marketing',
  'Enterprise Applications',
  'Web Development',
  'Project Management',
  'Domain Registrar',
  'Console Games',
  'Graphic Design',
  'CivicTech',
  'Desktop Apps',
  'PC Games',
  'Web Design',
  'Email',
  'Industrial Design',
  'Legal Tech',
  'Foundries',
  'Direct Marketing',
  'Big Data',
  '3D Technology',
  'Developer APIs',
  'Developer Tools',
  'CMS',
  'Video Editing',
  'Information and Communications Technology (ICT)',
  'PaaS',
  'Web Hosting',
  'Business Intelligence',
  'Operating Systems',
  'Data Center',
  'Video Games',
  'Embedded Software',
  'Application Performance Management',
  'Software Engineering',
  'Enterprise Resource Planning (ERP)',
  'Software',
  'Linux',
  'MMO Games',
  'A/B Testing',
  'Cloud Management',
  'Task Management',
  'Reading Apps',
  'UX Design',
  'Electronic Design Automation (EDA)',
  'Micro Lending',
  'Cloud Data Services',
  'Marketing Automation',
  'Cloud Storage',
  'Collaboration',
  'Data Mining',
  'Data Storage',
  'Information Technology',
  'Photo Editing',
  'Flash Storage',
  'Online Games',
  'File Sharing',
  'Presentation Software',
  'Cloud Infrastructure',
  'Database',
  'SaaS',
  'Data Center Automation',
  'Scheduling',
  'Sales Automation',
  'Cloud Security',
  'Developer Platform',
  'Industrial Engineering',
  'Cloud Computing',
  'Enterprise Software',
  'Archiving Service',
  'Business Information Systems',
  'Data Visualization',
  'Data Integration',
  'E-Signature',
  'E-Commerce Platforms',
  'Open Source',
  'Serious Games',
  'Productivity Tools',
  'Usability Testing',
  'Vertical Search',
  'Analytics',
  'IT Management',
  'Embedded Systems',
  'App Discovery',
  'Computer_Hardware_And_Services',
  'DSP',
  'Twitter',
  'Architecture',
  'Drone Management',
  'Industrial',
  '3D Printing',
  'WebOS',
  'DRM',
  'GPU',
  'Spam Filtering',
  'Content Syndication'],
 'Media_Traditional': ['Presentations',
  'News',
  'Photography',
  'Ad Network',
  'Radio',
  'Internet Radio',
  'Journalism',
  'Podcast',
  'Ad Server',
  'Celebrity',
  'EBooks',
  'Music Education',
  'Comics',
  'Outdoor Advertising',
  'Ad Exchange',
  'Art',
  'Ad Retargeting',
  'Ad Targeting',
  'Digital Entertainment',
  'TV Production',
  'Advertising',
  'Animation',
  'Independent Music',
  'Broadcasting',
  'Blogging Platforms',
  'Music Venues',
  'Advertising Platforms',
  'TV',
  'Music',
  'Music Streaming',
  'Publishing',
  'Fantasy Sports',
  'Politics',
  'Film',
  'Concerts',
  'Film Distribution',
  'Guides',
  'Film Production',
  'Media and Entertainment',
  'Digital Media',
  'Music Label',
  'Performing Arts',
  'Television',
  'Audiobooks',
  'Advertising',
  'Newspapers',
  'Television'],
 'Agriculture': ['Fruit',
  'Farmers Market',
  'Agriculture',
  'Animal Feed',
  'Aquaculture',
  'Timber',
  'AgTech',
  'Livestock',
  'Mining Technology',
  'Hydroponics',
  'Forestry',
  'Farming',
  'Cannabis',
  'Horticulture',
  'Mining',
  'Organic',
  'farming'],
 'Transportation': ['Car Sharing',
  'Logistics',
  'Sailing',
  'Air Transportation',
  'Shipping',
  'Diving',
  'Space Travel',
  'Water Transportation',
  'Parking',
  'Ride Sharing',
  'Travel',
  'Delivery',
  'Delivery Service',
  'Marine Transportation',
  'Autonomous Vehicles',
  'Taxi Service',
  'Fleet Management',
  'Automotive',
  'Same Day Delivery',
  'Last Mile Transportation',
  'Travel Agency',
  'In-Flight Entertainment',
  'Public Transportation',
  'Adventure Travel',
  'Tour Operator',
  'Electric Vehicle',
  'Transportation',
  'Railroad',
  'Courier Service',
  'Freight Service',
  'Recreational Vehicles',
  'Ports and Harbors',
  'Vending and Concessions',
  'Limousine Service',
  'Ferry Service'],
 'Healthcare': ['Veterinary',
  'Electronic Health Record (EHR)',
  'Pharmaceutical',
  'Genetics',
  'Neuroscience',
  'Biotechnology',
  'Quantified Self',
  'Elderly',
  'Physical Therapy',
  'Health',
  'Health Care',
  'Biopharma',
  'Child Care',
  'Social Assistance',
  'Life Science',
  'Medical',
  'Clinical Trials',
  'Bioinformatics',
  'Hospital',
  'Rehabilitation',
  'Wellness',
  'Alternative Medicine',
  'Health Diagnostics',
  'Elder Care',
  'Medical Professionals',
  'Psychology',
  'Mental Health',
  'Hotel',
  'Emergency Medicine',
  'Fitness',
  'Home Health Care',
  'Dental',
  'Hospitality',
  'Personal Health',
  'Cosmetic Surgery',
  'Medical Device',
  'Therapeutics',
  'Funerals',
  'Assistive Technology',
  'Nursing and Residential Care',
  'Diabetes',
  'First Aid',
  'mHealth',
  'Outpatient Care'],
 'Mobile_And_Telecommunications': ['App Marketing',
  'Mobile Devices',
  'iOS',
  'QR Codes',
  'Location Based Services',
  'Mobile Apps',
  'Apps',
  'Messaging',
  'VoIP',
  'Satellite Communication',
  'Android',
  'Telecommunications',
  'GPS',
  'Wireless',
  'Communication Hardware',
  'Communications Infrastructure',
  'Mobile',
  'Mobile Advertising',
  'Augmented Reality',
  'Video Conferencing',
  'Unified Communications',
  'NFC',
  'SMS',
  'Mobile Payments',
  'Wired Telecommunications',
  'Windows Phone'],
 'Financial': ['Asset Management',
  'Insurance',
  'Mobile Payments',
  'Retirement',
  'Funding Platform',
  'InsurTech',
  'Credit Cards',
  'Credit',
  'Consumer Research',
  'Financial Exchanges',
  'Angel Investment',
  'Risk Management',
  'Impact Investing',
  'Trading Platform',
  'Crowdfunding',
  'Health Insurance',
  'Emerging Markets',
  'Venture Capital',
  'Investment Management',
  'Bitcoin',
  'Debt Collections',
  'FinTech',
  'Consumer Lending',
  'Banking',
  'Debit Cards',
  'Life Insurance',
  'Hedge Funds',
  'Personal Finance',
  'Prediction Markets',
  'Lending',
  'Financial Services',
  'Leasing',
  'Ethereum',
  'Cryptocurrency',
  'Commercial Insurance',
  'Payments',
  'Blockchain',
  'Property Insurance',
  'Finance',
  'Auto Insurance',
  'Wealth Management',
  'Real Estate Investment',
  'Virtual Currency',
  'Freemium',
  'Stock Exchanges',
  'Credit Bureau',
  'Multi-level Marketing'],
 'Artificial_Intelligence': ['Text Analytics',
  'Smart Building',
  'Machine Learning',
  'Motion Capture',
  'Language Learning',
  'Quantum Computing',
  'Gamification',
  'Predictive Analytics',
  'Simulation',
  'Artificial Intelligence',
  'Speech Recognition',
  'Robotics',
  'Semantic Search',
  'Virtual Assistant',
  'Human Computer Interaction',
  'Natural Language Processing',
  'MOOC',
  'Virtual Reality',
  'Smart Cities',
  'Computer Vision',
  'Facial Recognition',
  'Personalization',
  'Smart Home',
  'Semantic Web',
  'Visual Search',
  'Real Time',
  'Image Recognition',
  'Intelligent Systems',
  'chatbots'],
 'Retail_NonInternetMobile': ['Toys',
  'Fast-Moving Consumer Goods',
  'Coupons',
  'Classifieds',
  'Jewelry',
  'Musical Instruments',
  'Beauty',
  'Social Shopping',
  'E-Commerce',
  'DIY',
  'Cosmetics',
  'Gift Card',
  'Sporting Goods',
  "Men's",
  'Consumer Goods',
  'Collectibles',
  'Gift Exchange',
  'Lingerie',
  'Collaborative Consumption',
  'Flowers',
  'Eyewear',
  'Consumer',
  'Shoes',
  'Auctions',
  'Fashion',
  'Rental',
  'Local Shopping',
  'Shopping',
  "Women's",
  'Gift',
  'Retail',
  'Gift Registry'],
 'Electronics': ['Advanced Materials',
  'Laser',
  'Industrial Design',
  'Foundries',
  'Sensor',
  'RFID',
  'Industrial Engineering',
  'Wearables',
  'Micro Lending',
  'Audio',
  'Product Design',
  'Industrial Automation',
  'Industrial Manufacturing',
  'Application Specific Integrated Circuit (ASIC)',
  'Mechanical Design',
  'Test and Measurement',
  'Consumer Research',
  'Electronics',
  'Semiconductor',
  'Mechanical Engineering',
  'Communication Hardware',
  'Consumer Electronics',
  'Optical Communication',
  'Digital Signage',
  'Lighting',
  'Google Glass'],
 'Food_And_Beverages': ['Recipes',
  'Tea',
  'Coffee',
  'Biofuel',
  'Boating',
  'Grocery',
  'Nutrition',
  'Baby',
  'Dietary Supplements',
  'Farming',
  'Winery',
  'Organic Food',
  'Pet',
  'Seafood',
  'Snack Food',
  'Nutraceutical',
  'Distillery',
  'Food Processing',
  'Wine And Spirits',
  'Confectionery',
  'Craft Beer',
  'Bakery',
  'Catering',
  'Restaurants',
  'Cooking',
  'Food and Beverage',
  'Brewing',
  'Food Delivery',
  'Food Trucks'],
 'Energy_And_Utilities': ['Wind Energy',
  'Fuel Cell',
  'Energy Efficiency',
  'Fuel',
  'Energy',
  'Battery',
  'Biomass Energy',
  'Natural Resources',
  'Fossil Fuels',
  'Electrical Distribution',
  'Infrastructure',
  'Energy Storage',
  'Solar',
  'Utilities',
  'Energy Management',
  'Clean Energy',
  'CleanTech',
  'Oil and Gas',
  'Renewable Energy',
  'Water',
  'Nuclear',
  'Power Grid',
  'Solar',
  'Wind Energy'],
 'Risk_And_Security': ['Commercial Insurance',
  'Biometrics',
  'Military',
  'Law Enforcement',
  'National Security',
  'Identity Management',
  'Intrusion Detection',
  'Public Safety',
  'Physical Security',
  'Homeland Security',
  'Privacy',
  'Reputation',
  'Compliance',
  'Network Security',
  'Security',
  'Cyber Security',
  'Fraud Detection',
  'Underserved Children',
  'Darknet',
  'Humanitarian'],
 'Computer_Hardware_And_Services': ['Office Administration',
  'Building Material',
  'Building Maintenance',
  'Industrial Design',
  'Foundries',
  'Windows',
  'Industrial Engineering',
  'IT Infrastructure',
  'Industrial Automation',
  'Retail Technology',
  'Application Specific Integrated Circuit (ASIC)',
  'Computer',
  'Computer Hardware',
  'Technical Support',
  'Private Cloud',
  'Network Hardware',
  'Hardware',
  'Point of Sale',
  'CAD',
  'Test and Measurement',
  'Field-Programmable Gate Array (FPGA)',
  'Nanotechnology'],
 'Real_Estate': ['Rental Property',
  'Property Management',
  'Housekeeping Service',
  'Homeless Shelter',
  'Property Development',
  'Residential',
  'Vacation Rental',
  'Home and Garden',
  'Home Services',
  'Hotel',
  'Home Improvement',
  'Resorts',
  'Timeshare',
  'Travel Accommodations',
  'Hospitality',
  'Real Estate',
  'Home Decor',
  'Home Renovation',
  'Commercial Real Estate',
  'Vacation Rentals'],
 'Internet': ['Dating',
  'Event Management',
  'ISP',
  'Classifieds',
  'Task Management',
  'Internet of Things',
  'E-Commerce',
  'Social Bookmarking',
  'Virtual World',
  'Browser Extensions',
  'Content Creators',
  'Content Delivery Network',
  'Games',
  'Product Design',
  'SEM',
  'Consumer Reviews',
  'Marketplace',
  'Social News',
  'Video Advertising',
  'Video Chat',
  'Social Media',
  'Content Discovery',
  'ICT',
  'Online Forums',
  'Consumer Applications',
  'Affiliate Marketing',
  'Casual Games',
  'File Sharing',
  'Web Apps',
  'Drones',
  'Mapping Services',
  'Crowdfunding',
  'Social',
  'Content Marketing',
  'Curated Web',
  'Communities',
  'Video',
  'Online Portals',
  'Blogging Platforms',
  'Lead Management',
  'Internet',
  'Video on Demand',
  'Foundries',
  'Private Social Networking',
  'Fantasy Sports',
  'Product Search',
  'Sharing Economy',
  'Video Streaming',
  'Gaming',
  'Direct Marketing',
  'Content',
  'Crowdsourcing',
  'Social Network',
  'Collectibles',
  'Search Engine',
  'Online Auctions',
  'Peer to Peer',
  'CMS',
  'Guides',
  'Cause Marketing',
  'Sponsorship',
  'SEO',
  'Consumer Internet',
  'Video Games',
  'Q&A',
  'Photo Sharing',
  'Handmade',
  'Social Media Advertising',
  'Web Browsers',
  'EdTech',
  'Navigation',
  'Internet Marketing',
  'Blogging Platforms',
  'Browser Extensions',
  'Casual Games',
  'Cause Marketing',
  'Classifieds',
  'Consumer Internet',
  'Crowdfunding',
  'Curated Web',
  'Dating',
  'E-Commerce',
  'File Sharing',
  'Games',
  'Internet Marketing',
  'Affiliate Marketing',
  'CMS',
  'Collectibles',
  'Direct Marketing',
  'Drones',
  'Event Management',
  'Fantasy Sports',
  'Foundries',
  'Gaming',
  'Guides',
  'Handmade',
  'Lead Management',
  'Online Forums',
  'Product Design',
  'Sponsorship',
  'Task Management',
  'Video Games'],
 'HR_People_Needs': ['Parenting',
  'Professional Networking',
  'Human Resources',
  'Social Recruiting',
  'Foundries',
  'Assisted Living',
  'Leisure',
  'Celebrity',
  'Skill Assessment',
  'Family',
  'Personal Branding',
  'Lifestyle',
  'Furniture',
  'Training',
  'Personal Development',
  'Employment',
  'Guides',
  'Distillery',
  'Staffing Agency',
  'Recruiting',
  'Equestrian',
  'Handmade',
  'Employee Benefits'],
 'Environmental_Services_and_Equipment': ['Water Purification',
  'Janitorial Service',
  'Printing',
  'Recycling',
  'Waste Management',
  'Green Consumer Goods',
  'Sustainability',
  'Pollution Control',
  'Landscaping',
  'Green Building',
  'Geospatial',
  'GreenTech',
  'Environmental Engineering',
  'Parks',
  'Packaging Services',
  'Marine Technology',
  'Environmental Consulting',
  'Assisted Living',
  'Celebrity',
  'Distillery',
  'Equestrian',
  'Foundries',
  'Furniture']}
